server:
    port: 8086

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: teamtool
            
logging:
  level:
    org.springframework.security: DEBUG
